[package]
name = "dbus-client-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
attribute-derive = "0.10.0"
manyhow = "0.11.1"
proc-macro2 = "1.0.86"
quote-use = "0.8.3"
syn = { version = "2.0.68", features = ["parsing"] }
